# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainform.ui'
#
# Created: Fri Feb 13 11:20:04 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class mainGUI(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(856, 652)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.hboxlayout = QtGui.QHBoxLayout(self.centralwidget)
        self.hboxlayout.setObjectName("hboxlayout")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.hboxlayout1 = QtGui.QHBoxLayout(self.tab)
        self.hboxlayout1.setMargin(1)
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.stackedWidget = QtGui.QStackedWidget(self.tab)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.vboxlayout = QtGui.QVBoxLayout(self.page)
        self.vboxlayout.setMargin(1)
        self.vboxlayout.setObjectName("vboxlayout")
        self.splitter = QtGui.QSplitter(self.page)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.tableWidget = QtGui.QTableWidget(self.splitter)
        self.tableWidget.setAutoScroll(True)
        self.tableWidget.setTabKeyNavigation(True)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.tableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.groupBox = QtGui.QGroupBox(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 160))
        self.groupBox.setObjectName("groupBox")
        self.vboxlayout1 = QtGui.QVBoxLayout(self.groupBox)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.hboxlayout2 = QtGui.QHBoxLayout()
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.radioButton = QtGui.QRadioButton(self.groupBox)
        self.radioButton.setObjectName("radioButton")
        self.hboxlayout2.addWidget(self.radioButton)
        self.radioButton_2 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_2.setObjectName("radioButton_2")
        self.hboxlayout2.addWidget(self.radioButton_2)
        self.radioButton_3 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_3.setChecked(True)
        self.radioButton_3.setObjectName("radioButton_3")
        self.hboxlayout2.addWidget(self.radioButton_3)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout2.addItem(spacerItem)
        self.repeatButton = QtGui.QPushButton(self.groupBox)
        self.repeatButton.setObjectName("repeatButton")
        self.hboxlayout2.addWidget(self.repeatButton)
        self.interceptCheck = QtGui.QPushButton(self.groupBox)
        self.interceptCheck.setCheckable(True)
        self.interceptCheck.setObjectName("interceptCheck")
        self.hboxlayout2.addWidget(self.interceptCheck)
        self.line = QtGui.QFrame(self.groupBox)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.hboxlayout2.addWidget(self.line)
        self.editRequestsButton = QtGui.QPushButton(self.groupBox)
        self.editRequestsButton.setObjectName("editRequestsButton")
        self.hboxlayout2.addWidget(self.editRequestsButton)
        self.deleteInViewButton = QtGui.QPushButton(self.groupBox)
        self.deleteInViewButton.setObjectName("deleteInViewButton")
        self.hboxlayout2.addWidget(self.deleteInViewButton)
        self.deleteSelectedButton = QtGui.QPushButton(self.groupBox)
        self.deleteSelectedButton.setObjectName("deleteSelectedButton")
        self.hboxlayout2.addWidget(self.deleteSelectedButton)
        self.vboxlayout1.addLayout(self.hboxlayout2)
        self.hboxlayout3 = QtGui.QHBoxLayout()
        self.hboxlayout3.setObjectName("hboxlayout3")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.hboxlayout3.addWidget(self.label)
        self.comboBox = QtGui.QComboBox(self.groupBox)
        self.comboBox.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem(QtCore.QString())
        self.hboxlayout3.addWidget(self.comboBox)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout3.addItem(spacerItem1)
        self.vboxlayout1.addLayout(self.hboxlayout3)
        self.hboxlayout4 = QtGui.QHBoxLayout()
        self.hboxlayout4.setObjectName("hboxlayout4")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.hboxlayout4.addWidget(self.label_2)
        self.comboBox_2 = QtGui.QComboBox(self.groupBox)
        self.comboBox_2.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem(QtCore.QString())
        self.hboxlayout4.addWidget(self.comboBox_2)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout4.addItem(spacerItem2)
        self.vboxlayout1.addLayout(self.hboxlayout4)
        self.tabResponse = QtGui.QTabWidget(self.splitter)
        self.tabResponse.setTabPosition(QtGui.QTabWidget.West)
        self.tabResponse.setObjectName("tabResponse")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridlayout = QtGui.QGridLayout(self.tab_3)
        self.gridlayout.setObjectName("gridlayout")
        self.requestEdit = QtGui.QTextEdit(self.tab_3)
        self.requestEdit.setReadOnly(True)
        self.requestEdit.setObjectName("requestEdit")
        self.gridlayout.addWidget(self.requestEdit, 0, 0, 1, 1)
        self.tabResponse.addTab(self.tab_3, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridlayout1 = QtGui.QGridLayout(self.tab_4)
        self.gridlayout1.setObjectName("gridlayout1")
        self.responseEdit = QtGui.QTextEdit(self.tab_4)
        self.responseEdit.setReadOnly(True)
        self.responseEdit.setObjectName("responseEdit")
        self.gridlayout1.addWidget(self.responseEdit, 0, 0, 1, 1)
        self.tabResponse.addTab(self.tab_4, "")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.hboxlayout5 = QtGui.QHBoxLayout(self.tab_5)
        self.hboxlayout5.setObjectName("hboxlayout5")
        self.tableWidget_2 = QtGui.QTableWidget(self.tab_5)
        self.tableWidget_2.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_2.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(2)
        self.tableWidget_2.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        self.hboxlayout5.addWidget(self.tableWidget_2)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout5.addItem(spacerItem3)
        self.tabResponse.addTab(self.tab_5, "")
        self.vboxlayout.addWidget(self.splitter)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName("page_2")
        self.vboxlayout2 = QtGui.QVBoxLayout(self.page_2)
        self.vboxlayout2.setObjectName("vboxlayout2")
        self.groupBox_2 = QtGui.QGroupBox(self.page_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.hboxlayout6 = QtGui.QHBoxLayout(self.groupBox_2)
        self.hboxlayout6.setObjectName("hboxlayout6")
        self.cookieEdit = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cookieEdit.sizePolicy().hasHeightForWidth())
        self.cookieEdit.setSizePolicy(sizePolicy)
        self.cookieEdit.setObjectName("cookieEdit")
        self.hboxlayout6.addWidget(self.cookieEdit)
        self.setCookieButton = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setCookieButton.sizePolicy().hasHeightForWidth())
        self.setCookieButton.setSizePolicy(sizePolicy)
        self.setCookieButton.setObjectName("setCookieButton")
        self.hboxlayout6.addWidget(self.setCookieButton)
        self.vboxlayout2.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.page_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.vboxlayout3 = QtGui.QVBoxLayout(self.groupBox_3)
        self.vboxlayout3.setObjectName("vboxlayout3")
        self.hboxlayout7 = QtGui.QHBoxLayout()
        self.hboxlayout7.setObjectName("hboxlayout7")
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.hboxlayout7.addWidget(self.label_4)
        self.substSrcEdit = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.substSrcEdit.sizePolicy().hasHeightForWidth())
        self.substSrcEdit.setSizePolicy(sizePolicy)
        self.substSrcEdit.setObjectName("substSrcEdit")
        self.hboxlayout7.addWidget(self.substSrcEdit)
        self.vboxlayout3.addLayout(self.hboxlayout7)
        self.hboxlayout8 = QtGui.QHBoxLayout()
        self.hboxlayout8.setObjectName("hboxlayout8")
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.hboxlayout8.addWidget(self.label_5)
        self.substDstEdit = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.substDstEdit.sizePolicy().hasHeightForWidth())
        self.substDstEdit.setSizePolicy(sizePolicy)
        self.substDstEdit.setObjectName("substDstEdit")
        self.hboxlayout8.addWidget(self.substDstEdit)
        self.vboxlayout3.addLayout(self.hboxlayout8)
        self.hboxlayout9 = QtGui.QHBoxLayout()
        self.hboxlayout9.setObjectName("hboxlayout9")
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout9.addItem(spacerItem4)
        self.substButton = QtGui.QPushButton(self.groupBox_3)
        self.substButton.setObjectName("substButton")
        self.hboxlayout9.addWidget(self.substButton)
        self.vboxlayout3.addLayout(self.hboxlayout9)
        self.vboxlayout2.addWidget(self.groupBox_3)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout2.addItem(spacerItem5)
        self.hboxlayout10 = QtGui.QHBoxLayout()
        self.hboxlayout10.setObjectName("hboxlayout10")
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout10.addItem(spacerItem6)
        self.doneButton = QtGui.QPushButton(self.page_2)
        self.doneButton.setObjectName("doneButton")
        self.hboxlayout10.addWidget(self.doneButton)
        self.vboxlayout2.addLayout(self.hboxlayout10)
        self.stackedWidget.addWidget(self.page_2)
        self.hboxlayout1.addWidget(self.stackedWidget)
        self.tabWidget.addTab(self.tab, "")
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.vboxlayout4 = QtGui.QVBoxLayout(self.tab_6)
        self.vboxlayout4.setObjectName("vboxlayout4")
        self.reqStatsTreeWidget = QtGui.QTreeWidget(self.tab_6)
        self.reqStatsTreeWidget.setAlternatingRowColors(True)
        self.reqStatsTreeWidget.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.reqStatsTreeWidget.setObjectName("reqStatsTreeWidget")
        self.vboxlayout4.addWidget(self.reqStatsTreeWidget)
        self.hboxlayout11 = QtGui.QHBoxLayout()
        self.hboxlayout11.setObjectName("hboxlayout11")
        self.updateReqStatsButton = QtGui.QPushButton(self.tab_6)
        self.updateReqStatsButton.setObjectName("updateReqStatsButton")
        self.hboxlayout11.addWidget(self.updateReqStatsButton)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout11.addItem(spacerItem7)
        self.vboxlayout4.addLayout(self.hboxlayout11)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.vboxlayout5 = QtGui.QVBoxLayout(self.tab_2)
        self.vboxlayout5.setObjectName("vboxlayout5")
        self.varStatsTreeWidget = QtGui.QTreeWidget(self.tab_2)
        self.varStatsTreeWidget.setAlternatingRowColors(True)
        self.varStatsTreeWidget.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.varStatsTreeWidget.setIndentation(30)
        self.varStatsTreeWidget.setObjectName("varStatsTreeWidget")
        self.vboxlayout5.addWidget(self.varStatsTreeWidget)
        self.hboxlayout12 = QtGui.QHBoxLayout()
        self.hboxlayout12.setObjectName("hboxlayout12")
        self.updateVarStatsButton = QtGui.QPushButton(self.tab_2)
        self.updateVarStatsButton.setObjectName("updateVarStatsButton")
        self.hboxlayout12.addWidget(self.updateVarStatsButton)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout12.addItem(spacerItem8)
        self.vboxlayout5.addLayout(self.hboxlayout12)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.vboxlayout6 = QtGui.QVBoxLayout(self.tab_7)
        self.vboxlayout6.setObjectName("vboxlayout6")
        self.groupBox_4 = QtGui.QGroupBox(self.tab_7)
        self.groupBox_4.setObjectName("groupBox_4")
        self.vboxlayout7 = QtGui.QVBoxLayout(self.groupBox_4)
        self.vboxlayout7.setObjectName("vboxlayout7")
        self.label_16 = QtGui.QLabel(self.groupBox_4)
        self.label_16.setObjectName("label_16")
        self.vboxlayout7.addWidget(self.label_16)
        self.hboxlayout13 = QtGui.QHBoxLayout()
        self.hboxlayout13.setObjectName("hboxlayout13")
        self.label_6 = QtGui.QLabel(self.groupBox_4)
        self.label_6.setObjectName("label_6")
        self.hboxlayout13.addWidget(self.label_6)
        self.getsignEdit = QtGui.QLineEdit(self.groupBox_4)
        self.getsignEdit.setObjectName("getsignEdit")
        self.hboxlayout13.addWidget(self.getsignEdit)
        self.vboxlayout7.addLayout(self.hboxlayout13)
        self.label_17 = QtGui.QLabel(self.groupBox_4)
        self.label_17.setObjectName("label_17")
        self.vboxlayout7.addWidget(self.label_17)
        self.hboxlayout14 = QtGui.QHBoxLayout()
        self.hboxlayout14.setObjectName("hboxlayout14")
        self.label_8 = QtGui.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.hboxlayout14.addWidget(self.label_8)
        self.headersignEdit = QtGui.QLineEdit(self.groupBox_4)
        self.headersignEdit.setObjectName("headersignEdit")
        self.hboxlayout14.addWidget(self.headersignEdit)
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        self.label_7.setObjectName("label_7")
        self.hboxlayout14.addWidget(self.label_7)
        self.valuesignEdit = QtGui.QLineEdit(self.groupBox_4)
        self.valuesignEdit.setObjectName("valuesignEdit")
        self.hboxlayout14.addWidget(self.valuesignEdit)
        self.vboxlayout7.addLayout(self.hboxlayout14)
        self.vboxlayout6.addWidget(self.groupBox_4)
        self.groupBox_5 = QtGui.QGroupBox(self.tab_7)
        self.groupBox_5.setObjectName("groupBox_5")
        self.vboxlayout8 = QtGui.QVBoxLayout(self.groupBox_5)
        self.vboxlayout8.setObjectName("vboxlayout8")
        self.label_9 = QtGui.QLabel(self.groupBox_5)
        self.label_9.setObjectName("label_9")
        self.vboxlayout8.addWidget(self.label_9)
        self.label_15 = QtGui.QLabel(self.groupBox_5)
        self.label_15.setObjectName("label_15")
        self.vboxlayout8.addWidget(self.label_15)
        self.pathlimitEdit = QtGui.QLineEdit(self.groupBox_5)
        self.pathlimitEdit.setObjectName("pathlimitEdit")
        self.vboxlayout8.addWidget(self.pathlimitEdit)
        self.vboxlayout6.addWidget(self.groupBox_5)
        self.groupBox_6 = QtGui.QGroupBox(self.tab_7)
        self.groupBox_6.setObjectName("groupBox_6")
        self.vboxlayout9 = QtGui.QVBoxLayout(self.groupBox_6)
        self.vboxlayout9.setObjectName("vboxlayout9")
        self.label_10 = QtGui.QLabel(self.groupBox_6)
        self.label_10.setObjectName("label_10")
        self.vboxlayout9.addWidget(self.label_10)
        self.proxyEdit = QtGui.QLineEdit(self.groupBox_6)
        self.proxyEdit.setObjectName("proxyEdit")
        self.vboxlayout9.addWidget(self.proxyEdit)
        self.vboxlayout6.addWidget(self.groupBox_6)
        self.groupBox_7 = QtGui.QGroupBox(self.tab_7)
        self.groupBox_7.setObjectName("groupBox_7")
        self.hboxlayout15 = QtGui.QHBoxLayout(self.groupBox_7)
        self.hboxlayout15.setObjectName("hboxlayout15")
        self.label_18 = QtGui.QLabel(self.groupBox_7)
        self.label_18.setObjectName("label_18")
        self.hboxlayout15.addWidget(self.label_18)
        self.portSpin = QtGui.QSpinBox(self.groupBox_7)
        self.portSpin.setMinimum(1)
        self.portSpin.setMaximum(65535)
        self.portSpin.setProperty("value", QtCore.QVariant(8008))
        self.portSpin.setObjectName("portSpin")
        self.hboxlayout15.addWidget(self.portSpin)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout15.addItem(spacerItem9)
        self.vboxlayout6.addWidget(self.groupBox_7)
        spacerItem10 = QtGui.QSpacerItem(816, 131, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout6.addItem(spacerItem10)
        self.hboxlayout16 = QtGui.QHBoxLayout()
        self.hboxlayout16.setObjectName("hboxlayout16")
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout16.addItem(spacerItem11)
        self.configApplyButton = QtGui.QPushButton(self.tab_7)
        self.configApplyButton.setObjectName("configApplyButton")
        self.hboxlayout16.addWidget(self.configApplyButton)
        self.vboxlayout6.addLayout(self.hboxlayout16)
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.vboxlayout10 = QtGui.QVBoxLayout(self.tab_8)
        self.vboxlayout10.setObjectName("vboxlayout10")
        self.hboxlayout17 = QtGui.QHBoxLayout()
        self.hboxlayout17.setObjectName("hboxlayout17")
        self.label_11 = QtGui.QLabel(self.tab_8)
        self.label_11.setObjectName("label_11")
        self.hboxlayout17.addWidget(self.label_11)
        self.pluginCombo = QtGui.QComboBox(self.tab_8)
        self.pluginCombo.setObjectName("pluginCombo")
        self.hboxlayout17.addWidget(self.pluginCombo)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout17.addItem(spacerItem12)
        self.resetCacheButton = QtGui.QPushButton(self.tab_8)
        self.resetCacheButton.setObjectName("resetCacheButton")
        self.hboxlayout17.addWidget(self.resetCacheButton)
        self.ToHTMLButton = QtGui.QPushButton(self.tab_8)
        self.ToHTMLButton.setObjectName("ToHTMLButton")
        self.hboxlayout17.addWidget(self.ToHTMLButton)
        self.ToXMLButton = QtGui.QPushButton(self.tab_8)
        self.ToXMLButton.setObjectName("ToXMLButton")
        self.hboxlayout17.addWidget(self.ToXMLButton)
        self.vboxlayout10.addLayout(self.hboxlayout17)
        self.line_2 = QtGui.QFrame(self.tab_8)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.vboxlayout10.addWidget(self.line_2)
        self.stackedWidget_2 = QtGui.QStackedWidget(self.tab_8)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName("page_3")
        self.vboxlayout11 = QtGui.QVBoxLayout(self.page_3)
        self.vboxlayout11.setMargin(1)
        self.vboxlayout11.setObjectName("vboxlayout11")
        self.hboxlayout18 = QtGui.QHBoxLayout()
        self.hboxlayout18.setObjectName("hboxlayout18")
        self.hboxlayout19 = QtGui.QHBoxLayout()
        self.hboxlayout19.setObjectName("hboxlayout19")
        self.hboxlayout18.addLayout(self.hboxlayout19)
        self.vboxlayout11.addLayout(self.hboxlayout18)
        self.stackedWidget_2.addWidget(self.page_3)
        self.vboxlayout10.addWidget(self.stackedWidget_2)
        self.tabWidget.addTab(self.tab_8, "")
        self.tab_9 = QtGui.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.hboxlayout20 = QtGui.QHBoxLayout(self.tab_9)
        self.hboxlayout20.setObjectName("hboxlayout20")
        self.vboxlayout12 = QtGui.QVBoxLayout()
        self.vboxlayout12.setObjectName("vboxlayout12")
        self.hboxlayout21 = QtGui.QHBoxLayout()
        self.hboxlayout21.setObjectName("hboxlayout21")
        self.label_12 = QtGui.QLabel(self.tab_9)
        self.label_12.setObjectName("label_12")
        self.hboxlayout21.addWidget(self.label_12)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout21.addItem(spacerItem13)
        self.vboxlayout12.addLayout(self.hboxlayout21)
        self.bgLogTextEdit = QtGui.QTextEdit(self.tab_9)
        self.bgLogTextEdit.setReadOnly(True)
        self.bgLogTextEdit.setObjectName("bgLogTextEdit")
        self.vboxlayout12.addWidget(self.bgLogTextEdit)
        self.hboxlayout20.addLayout(self.vboxlayout12)
        self.vboxlayout13 = QtGui.QVBoxLayout()
        self.vboxlayout13.setObjectName("vboxlayout13")
        self.hboxlayout22 = QtGui.QHBoxLayout()
        self.hboxlayout22.setObjectName("hboxlayout22")
        self.label_13 = QtGui.QLabel(self.tab_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.hboxlayout22.addWidget(self.label_13)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.hboxlayout22.addItem(spacerItem14)
        self.vboxlayout13.addLayout(self.hboxlayout22)
        self.pluginStatusTable = QtGui.QTableWidget(self.tab_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pluginStatusTable.sizePolicy().hasHeightForWidth())
        self.pluginStatusTable.setSizePolicy(sizePolicy)
        self.pluginStatusTable.setMaximumSize(QtCore.QSize(220, 16777215))
        self.pluginStatusTable.setObjectName("pluginStatusTable")
        self.pluginStatusTable.setColumnCount(2)
        self.pluginStatusTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.pluginStatusTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.pluginStatusTable.setHorizontalHeaderItem(1, item)
        self.vboxlayout13.addWidget(self.pluginStatusTable)
        self.hboxlayout20.addLayout(self.vboxlayout13)
        self.tabWidget.addTab(self.tab_9, "")
        self.tab_10 = QtGui.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.gridlayout2 = QtGui.QGridLayout(self.tab_10)
        self.gridlayout2.setMargin(2)
        self.gridlayout2.setObjectName("gridlayout2")
        self.splitter_4 = QtGui.QSplitter(self.tab_10)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName("splitter_4")
        self.layoutWidget = QtGui.QWidget(self.splitter_4)
        self.layoutWidget.setObjectName("layoutWidget")
        self.vboxlayout14 = QtGui.QVBoxLayout(self.layoutWidget)
        self.vboxlayout14.setObjectName("vboxlayout14")
        self.hboxlayout23 = QtGui.QHBoxLayout()
        self.hboxlayout23.setObjectName("hboxlayout23")
        self.label_19 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setObjectName("label_19")
        self.hboxlayout23.addWidget(self.label_19)
        self.requrlEdit = QtGui.QLineEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.requrlEdit.sizePolicy().hasHeightForWidth())
        self.requrlEdit.setSizePolicy(sizePolicy)
        self.requrlEdit.setMaxLength(5)
        self.requrlEdit.setObjectName("requrlEdit")
        self.hboxlayout23.addWidget(self.requrlEdit)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout23.addItem(spacerItem15)
        self.reqperformButton = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reqperformButton.sizePolicy().hasHeightForWidth())
        self.reqperformButton.setSizePolicy(sizePolicy)
        self.reqperformButton.setObjectName("reqperformButton")
        self.hboxlayout23.addWidget(self.reqperformButton)
        self.vboxlayout14.addLayout(self.hboxlayout23)
        self.label_25 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setObjectName("label_25")
        self.vboxlayout14.addWidget(self.label_25)
        self.reqTextEdit = QtGui.QTextEdit(self.layoutWidget)
        self.reqTextEdit.setObjectName("reqTextEdit")
        self.vboxlayout14.addWidget(self.reqTextEdit)
        self.layoutWidget1 = QtGui.QWidget(self.splitter_4)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.vboxlayout15 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.vboxlayout15.setObjectName("vboxlayout15")
        self.label_20 = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setObjectName("label_20")
        self.vboxlayout15.addWidget(self.label_20)
        self.splitter_3 = QtGui.QSplitter(self.layoutWidget1)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.responseTextEdit = QtGui.QTextEdit(self.splitter_3)
        self.responseTextEdit.setEnabled(True)
        self.responseTextEdit.setReadOnly(True)
        self.responseTextEdit.setObjectName("responseTextEdit")
        self.layoutWidget2 = QtGui.QWidget(self.splitter_3)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.vboxlayout16 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.vboxlayout16.setObjectName("vboxlayout16")
        self.hboxlayout24 = QtGui.QHBoxLayout()
        self.hboxlayout24.setObjectName("hboxlayout24")
        self.label_22 = QtGui.QLabel(self.layoutWidget2)
        self.label_22.setObjectName("label_22")
        self.hboxlayout24.addWidget(self.label_22)
        self.responselenghtEdit = QtGui.QLineEdit(self.layoutWidget2)
        self.responselenghtEdit.setEnabled(True)
        self.responselenghtEdit.setReadOnly(True)
        self.responselenghtEdit.setObjectName("responselenghtEdit")
        self.hboxlayout24.addWidget(self.responselenghtEdit)
        self.vboxlayout16.addLayout(self.hboxlayout24)
        self.hboxlayout25 = QtGui.QHBoxLayout()
        self.hboxlayout25.setObjectName("hboxlayout25")
        self.label_23 = QtGui.QLabel(self.layoutWidget2)
        self.label_23.setObjectName("label_23")
        self.hboxlayout25.addWidget(self.label_23)
        self.responsewordsEdit = QtGui.QLineEdit(self.layoutWidget2)
        self.responsewordsEdit.setEnabled(True)
        self.responsewordsEdit.setReadOnly(True)
        self.responsewordsEdit.setObjectName("responsewordsEdit")
        self.hboxlayout25.addWidget(self.responsewordsEdit)
        self.vboxlayout16.addLayout(self.hboxlayout25)
        self.hboxlayout26 = QtGui.QHBoxLayout()
        self.hboxlayout26.setObjectName("hboxlayout26")
        self.label_21 = QtGui.QLabel(self.layoutWidget2)
        self.label_21.setObjectName("label_21")
        self.hboxlayout26.addWidget(self.label_21)
        self.responselinesEdit = QtGui.QLineEdit(self.layoutWidget2)
        self.responselinesEdit.setEnabled(True)
        self.responselinesEdit.setReadOnly(True)
        self.responselinesEdit.setObjectName("responselinesEdit")
        self.hboxlayout26.addWidget(self.responselinesEdit)
        self.vboxlayout16.addLayout(self.hboxlayout26)
        self.hboxlayout27 = QtGui.QHBoxLayout()
        self.hboxlayout27.setObjectName("hboxlayout27")
        self.label_24 = QtGui.QLabel(self.layoutWidget2)
        self.label_24.setObjectName("label_24")
        self.hboxlayout27.addWidget(self.label_24)
        self.responsemd5Edit = QtGui.QLineEdit(self.layoutWidget2)
        self.responsemd5Edit.setEnabled(True)
        self.responsemd5Edit.setReadOnly(True)
        self.responsemd5Edit.setObjectName("responsemd5Edit")
        self.hboxlayout27.addWidget(self.responsemd5Edit)
        self.vboxlayout16.addLayout(self.hboxlayout27)
        self.diffButton = QtGui.QPushButton(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.diffButton.sizePolicy().hasHeightForWidth())
        self.diffButton.setSizePolicy(sizePolicy)
        self.diffButton.setCheckable(True)
        self.diffButton.setObjectName("diffButton")
        self.vboxlayout16.addWidget(self.diffButton)
        spacerItem16 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout16.addItem(spacerItem16)
        self.vboxlayout15.addWidget(self.splitter_3)
        self.gridlayout2.addWidget(self.splitter_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_10, "")
        self.tab_11 = QtGui.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.tab_11)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem17)
        self.startCrawlButton = QtGui.QPushButton(self.tab_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startCrawlButton.sizePolicy().hasHeightForWidth())
        self.startCrawlButton.setSizePolicy(sizePolicy)
        self.startCrawlButton.setMinimumSize(QtCore.QSize(200, 70))
        self.startCrawlButton.setCheckable(True)
        self.startCrawlButton.setObjectName("startCrawlButton")
        self.horizontalLayout_4.addWidget(self.startCrawlButton)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem18)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem19)
        self.crawlPluginCheck = QtGui.QCheckBox(self.tab_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.crawlPluginCheck.sizePolicy().hasHeightForWidth())
        self.crawlPluginCheck.setSizePolicy(sizePolicy)
        self.crawlPluginCheck.setObjectName("crawlPluginCheck")
        self.horizontalLayout_5.addWidget(self.crawlPluginCheck)
        spacerItem20 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem20)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtGui.QLabel(self.tab_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.domainLimitEdit = QtGui.QLineEdit(self.tab_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.domainLimitEdit.sizePolicy().hasHeightForWidth())
        self.domainLimitEdit.setSizePolicy(sizePolicy)
        self.domainLimitEdit.setObjectName("domainLimitEdit")
        self.horizontalLayout.addWidget(self.domainLimitEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.frame = QtGui.QFrame(self.tab_11)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.crawlProgress = QtGui.QProgressBar(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.crawlProgress.sizePolicy().hasHeightForWidth())
        self.crawlProgress.setSizePolicy(sizePolicy)
        self.crawlProgress.setMinimumSize(QtCore.QSize(200, 0))
        self.crawlProgress.setProperty("value", QtCore.QVariant(0))
        self.crawlProgress.setObjectName("crawlProgress")
        self.horizontalLayout_2.addWidget(self.crawlProgress)
        self.progressLabel = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressLabel.sizePolicy().hasHeightForWidth())
        self.progressLabel.setSizePolicy(sizePolicy)
        self.progressLabel.setObjectName("progressLabel")
        self.horizontalLayout_2.addWidget(self.progressLabel)
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem21 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem21)
        self.crawlResetButton = QtGui.QPushButton(self.tab_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.crawlResetButton.sizePolicy().hasHeightForWidth())
        self.crawlResetButton.setSizePolicy(sizePolicy)
        self.crawlResetButton.setObjectName("crawlResetButton")
        self.horizontalLayout_6.addWidget(self.crawlResetButton)
        spacerItem22 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem22)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        spacerItem23 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem23)
        self.label_14 = QtGui.QLabel(self.tab_11)
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        self.groupBox_8 = QtGui.QGroupBox(self.tab_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.crawlFormsList = QtGui.QListWidget(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.crawlFormsList.sizePolicy().hasHeightForWidth())
        self.crawlFormsList.setSizePolicy(sizePolicy)
        self.crawlFormsList.setAlternatingRowColors(True)
        self.crawlFormsList.setObjectName("crawlFormsList")
        self.horizontalLayout_3.addWidget(self.crawlFormsList)
        self.horizontalLayout_7.addWidget(self.groupBox_8)
        self.tabWidget.addTab(self.tab_11, "")
        self.hboxlayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 856, 26))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusbar.sizePolicy().hasHeightForWidth())
        self.statusbar.setSizePolicy(sizePolicy)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionOpen_2 = QtGui.QAction(MainWindow)
        self.actionOpen_2.setObjectName("actionOpen_2")
        self.actionExit_2 = QtGui.QAction(MainWindow)
        self.actionExit_2.setObjectName("actionExit_2")
        self.actionSave_session = QtGui.QAction(MainWindow)
        self.actionSave_session.setObjectName("actionSave_session")
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuHelp.menuAction())

        #self.retranslateUi(MainWindow)
        #self.tabWidget.setCurrentIndex(3)
        #self.stackedWidget.setCurrentIndex(0)
        #self.tabResponse.setCurrentIndex(2)
        #self.stackedWidget_2.setCurrentIndex(0)
        #QtCore.QObject.connect(self.menubar, QtCore.SIGNAL("highlighted(int)"), self.tabWidget.setCurrentPage)
        #QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "ProxyStrike v2.1", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Method", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Target", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Url", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Cookies", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Select", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton.setText(QtGui.QApplication.translate("MainWindow", "Get", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_2.setText(QtGui.QApplication.translate("MainWindow", "Post", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_3.setText(QtGui.QApplication.translate("MainWindow", "All", None, QtGui.QApplication.UnicodeUTF8))
        self.repeatButton.setText(QtGui.QApplication.translate("MainWindow", "Repeat", None, QtGui.QApplication.UnicodeUTF8))
        self.interceptCheck.setText(QtGui.QApplication.translate("MainWindow", "Intercept", None, QtGui.QApplication.UnicodeUTF8))
        self.editRequestsButton.setText(QtGui.QApplication.translate("MainWindow", "Edit requests in view", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteInViewButton.setText(QtGui.QApplication.translate("MainWindow", "Delete requests in view", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteSelectedButton.setText(QtGui.QApplication.translate("MainWindow", "Delete selected requests", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Target :", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "All", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Path :", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(0, QtGui.QApplication.translate("MainWindow", "All", None, QtGui.QApplication.UnicodeUTF8))
        self.tabResponse.setTabText(self.tabResponse.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Requests", None, QtGui.QApplication.UnicodeUTF8))
        self.tabResponse.setTabText(self.tabResponse.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "Responses", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_2.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Variable", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_2.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.tabResponse.setTabText(self.tabResponse.indexOf(self.tab_5), QtGui.QApplication.translate("MainWindow", "Variables", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:13pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">This action, sets a new cookie for the </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">visible requests in the requests table.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Set Cookie", None, QtGui.QApplication.UnicodeUTF8))
        self.setCookieButton.setText(QtGui.QApplication.translate("MainWindow", "Set cookie", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Regex request substitution", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Substitute:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "by:", None, QtGui.QApplication.UnicodeUTF8))
        self.substButton.setText(QtGui.QApplication.translate("MainWindow", "Substitute", None, QtGui.QApplication.UnicodeUTF8))
        self.doneButton.setText(QtGui.QApplication.translate("MainWindow", "Done", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Comms", None, QtGui.QApplication.UnicodeUTF8))
        self.reqStatsTreeWidget.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Request", None, QtGui.QApplication.UnicodeUTF8))
        self.reqStatsTreeWidget.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Variable set", None, QtGui.QApplication.UnicodeUTF8))
        self.updateReqStatsButton.setText(QtGui.QApplication.translate("MainWindow", "Update stats", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QtGui.QApplication.translate("MainWindow", "Request Stats", None, QtGui.QApplication.UnicodeUTF8))
        self.varStatsTreeWidget.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Variable", None, QtGui.QApplication.UnicodeUTF8))
        self.varStatsTreeWidget.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Values", None, QtGui.QApplication.UnicodeUTF8))
        self.updateVarStatsButton.setText(QtGui.QApplication.translate("MainWindow", "Update stats", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Variable Stats", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "GET and HEADERS Sign", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Proxy Strike can append values to the url while you are browsing web pages.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Get (ex: &myvar=myval)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "You can add or modify existing headers while browsing. Eg: User-agent: FakeBrowser", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Header", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("MainWindow", "Path limit", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Proxy will allow acces only to paths matching the following pattern (regex):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "eg: /pages/page[0-9]{2}.html            (will only allow access to urls containing /pages/pageXX.html where XX are numbers)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("MainWindow", "Use proxy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Set proxy server (eg. localhost:8080)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("MainWindow", "ProxyStrike listen port", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Listen port", None, QtGui.QApplication.UnicodeUTF8))
        self.configApplyButton.setText(QtGui.QApplication.translate("MainWindow", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), QtGui.QApplication.translate("MainWindow", "Config", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Plugin selection: ", None, QtGui.QApplication.UnicodeUTF8))
        self.resetCacheButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">You will be able to attack the same url more than once.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.resetCacheButton.setText(QtGui.QApplication.translate("MainWindow", "Reset cache", None, QtGui.QApplication.UnicodeUTF8))
        self.ToHTMLButton.setText(QtGui.QApplication.translate("MainWindow", "Export HTML", None, QtGui.QApplication.UnicodeUTF8))
        self.ToXMLButton.setText(QtGui.QApplication.translate("MainWindow", "Export XML", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), QtGui.QApplication.translate("MainWindow", "Plugins", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Log output:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Running threads:", None, QtGui.QApplication.UnicodeUTF8))
        self.pluginStatusTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Plugin", None, QtGui.QApplication.UnicodeUTF8))
        self.pluginStatusTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "#threads", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), QtGui.QApplication.translate("MainWindow", "Log", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Schema (http/https):", None, QtGui.QApplication.UnicodeUTF8))
        self.reqperformButton.setText(QtGui.QApplication.translate("MainWindow", "Perform", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "Raw request", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Response", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Lenght", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "Words", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "Lines", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "Md5", None, QtGui.QApplication.UnicodeUTF8))
        self.diffButton.setText(QtGui.QApplication.translate("MainWindow", "Show differences", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_10), QtGui.QApplication.translate("MainWindow", "Repeat Request", None, QtGui.QApplication.UnicodeUTF8))
        self.startCrawlButton.setText(QtGui.QApplication.translate("MainWindow", "Stopped", None, QtGui.QApplication.UnicodeUTF8))
        self.crawlPluginCheck.setText(QtGui.QApplication.translate("MainWindow", "Crawl using plugins", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Url:", None, QtGui.QApplication.UnicodeUTF8))
        self.progressLabel.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.crawlResetButton.setText(QtGui.QApplication.translate("MainWindow", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; vertical-align:sub;\">Crawling process: The crawling process is performed by TWO threads<br />to avoid web server overloading.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:16pt; vertical-align:sub;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:16pt; vertical-align:sub;\">The urls detected can be forwarded to enabled plugins.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:16pt; vertical-align:sub;\">Moreover detected forms are shown in the table and can be filled </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:16pt; vertical-align:sub;\">manually by double-clicking on each link. Enjoy!</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("MainWindow", "Uniq Froms", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_11), QtGui.QApplication.translate("MainWindow", "Crawler", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_2.setText(QtGui.QApplication.translate("MainWindow", "Open session", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit_2.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_session.setText(QtGui.QApplication.translate("MainWindow", "Save session", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))

